services:
  backend:
    image: python:3.13-slim
    working_dir: /app
    volumes:
      - ./backend:/app
    command: ["sh", "-c", "pip install -r requirements.txt && python app.py"]
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "${BACKEND_PORT}:5000"
    restart: unless-stopped

  frontend:
    image: node:22-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["sh", "-c", "npm i && npm run build && npm run serve"]
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - HOST=0.0.0.0
      - REACT_APP_BACKEND_URI=${REACT_APP_BACKEND_URI}
    depends_on:
      - backend
    restart: unless-stopped
